### ISSUE TITLE
[homework] 20201030

### ISSUE THREAD

**Issue by filoscoder** [filoscoder/fe-soon#15]
Hi @jkim237 :)
## **이번주 숙제입니다:** 다음주 (월) 20201030 일까지 해주시고, 같이 풀어나갑시다!

> ### 항상! 작업 전/ 후 `git fetch upstream master` 잊지마세요! :) 
> 코딩 후 `PR`을 작성하여 제출해주세요!

# Language: Javascript
> [공식문서](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps) <= now, this is your friend. Say hi!

### 1. History
- Check this [video](https://www.youtube.com/watch?v=wcsVjmHrUQg)
- Answer these questions:
  - A) What is a `Programming Language`? (check [this](https://news.codecademy.com/programming-languages/) article)
  - B) What is `Javascript`? (One sentence is enough!)
  - C) What are the `pro` and `cons` of Javascript? (Just list a few ;))

### 2. Syntax: 
Follow the content of this [site](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Variables)
- Variables
- Variables types (data types): primitives

## Learn Javascript online
> Choose one or another site you want and keep learning. A solid base is very important!

- [Codecademy](https://www.codecademy.com/learn/introduction-to-javascript)
- [FreeCodeCamp](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/)

**Comment by jkim237** [comment]
## A1: What is a Programming Language? 
Programming Language is a translator between the binary codes(Computer's language) and the human language. There are 2 types of programming languages. High-level languages and low-level languages. High-level languages are more like human languages. So, they're easier to understand for human beings. But sometimes, they're slower than the low-level languages. 

## A2: What is Javascript?
The programming language that can make the website to interact with the users.

## A3: What are the pro and cons of Javascript?
##### Pros: 
- Easy to Understand and use
- It's fast
- Versatility
- Server Load

##### Pros: 
- Client-side Security
- Browser Support
- Single Inheritance
