### ISSUE TITLE
first markdown.md

### ISSUE THREAD

**Issue by jkim237** [filoscoder/fe-soon#4]
## First Markdown Tryout
- 01
- 02
- 03
- 04

[anchor01](#Checklist)

| 01 | 02 | 03 |
|---|---|---|
| ![꽃](https://user-images.githubusercontent.com/45983469/95037831-4e9cda80-0707-11eb-8505-658580eaad8d.jpeg) | ![Rotating_earth_(large)](https://user-images.githubusercontent.com/45983469/95038414-01ba0380-0709-11eb-8e1c-a93702278374.gif) | ![simpson](https://user-images.githubusercontent.com/45983469/95038319-c4ee0c80-0708-11eb-99b1-a9376eb98990.gif) |

**Bold Text 01**
1. `Something`
2. `Something2`

## Related Issue
> Something
img
Assignment3 https://github.com/filoscoder/fe-soon/issues/3

**Bold Text 02**
## Test
WIP
## Checklist
- [ ]Did I do it right?
- [ ]Did I do it right?
- [x] Did I do it right?

[test](#anchor01)

**Comment by filoscoder** [comment]
Great job @jkim237!
Please add 3 more things:
- Add an [Anchor](https://talk.commonmark.org/t/anchors-in-markdown/247) pointing the _Issue example_ you were cloning
- Add a screenshot image and GIF animation
- [Mention](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/autolinked-references-and-urls) the [[homework] 20200928](https://github.com/filoscoder/fe-soon/issues/3) issue as a reference inside "**Related Issue**" field

**Comment by filoscoder** [comment]
LGTM!
