### ISSUE TITLE
JK studio homepage

### ISSUE THREAD

**Issue by filoscoder** [filoscoder/fe-soon#8]
# Project: JK Studio landing page

- [x] Create _private_ repository 
- [x] Create wireframe & layout design
- [x] Define front stack
- [x] Manage project with git work flow
- [x] Develop!

**Comment by jkim237** [comment]
## Question

css에서 Media Query로 Grid를 조절했는데 아래 이미지처럼 적용이 안됩니다. 이유를 알 수 있을까요?

| CSS | Web |
|:----------|:----------:|
| <img width="1296" alt="Screen Shot 2020-10-16 at 4 18 08 AM" src="https://user-images.githubusercontent.com/45983469/96176002-b1437100-0f66-11eb-8f93-4ef43fd90622.png"> | <img width="1841" alt="Screen Shot 2020-10-16 at 4 18 30 AM" src="https://user-images.githubusercontent.com/45983469/96176012-b56f8e80-0f66-11eb-9733-aaa70c5090c7.png"> |

**Comment by filoscoder** [comment]
>css에서 Media Query로 Grid를 조절했는데 ...

_"조절하셨다는"_ 말은 `padding-left: 60%;` 이값을 넣었는데 적용이 안됬다는 말인가요?
만약 이게 맞으시다면,  `padding-left: 60%;` CSS 값이 어떤 _`Selector`_ 에 지정 되어 있는지 확인해보시면 알 것 같아요!
```SCSS
/* Selector */
  .nav__column__course {
        padding-left: 60%;
  }
```

![스크린샷 2020-10-17 오후 3 35 31](https://user-images.githubusercontent.com/50701501/96330271-f662c280-108e-11eb-8801-5e7dcb9b1b80.png)

**Comment by jkim237** [comment]
아, 아뇨 grid가 풀리질 않네요. 375px밑으로는 grid를 1부터 8까지 지정했는데 먹질 않아서요ㅠㅜ

**Comment by jkim237** [comment]
!important 넣는걸로 해결했습니다:)
